### ISSUE TITLE
Recipe App Kanban board

### ISSUE THREAD

**Issue by nimplay** [williamscch/recipeapp#11]
### Description
This is the Kanban board for the recipe app project using Ruby and Rails.

**Participants:**

Github: [Willian Colmenares](https://github.com/williamscch)
Github: [Nimrod Acosta](https://github.com/nimplay)

**Poject link*
https://github.com/williamscch/recipeapp/projects/1

**Comment by omar-muhamad** [comment]
# Changes Required ♻️
### Hi @nimplay and @williamscch,

Nice job, you are almost there.

![](https://media.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif)

## (Changes Required) Aspects to improve: ♻️

- [ ] Please add a proper description to all Kanban cards with the changes you will do in it, because there are a lot of cards that have no description.

![image](https://user-images.githubusercontent.com/68796232/200361095-4952be5c-2226-4b37-9019-0794567b1892.png)

## [Optional] suggestions:

- Nothing to mention.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by danmainah** [comment]
Hi @nimplay and @williamscch , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 🎉 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
